### ISSUE TITLE
Produce useful error messages and support logging in the notification framework

### ISSUE THREAD

**Issue by gervarro** [eMoflon/emoflon-ibex-democles#18]
The notification framework should produce useful error messages in the exceptions, which should result in meaningful log messages.

**Comment by anthonyanjorin** [comment]
Just to add a concrete example:  at the moment if you delete model elements in such a way that dangling objects without any container are left over, you get a Join-Failed exception with no explanation.  While I agree that such a deletion is problematic and should be flagged as such (as opposed to just quietly ignoring it), a message that mentions the problematic objects with an explanation would be nice.

**Comment by anthonyanjorin** [comment]
I now have someone in industry trying to use IBeX and the problem with "RuntimeExceptions" is really bad.  We should try to improve the type and message of all exceptions.  For example:

`Exception in thread "main" java.lang.RuntimeException 
        at org.gervarro.democles.notification.emf.NotificationModule.issueNotificationsForInsertion(NotificationModule.java:174) 
        at org.gervarro.democles.incremental.emf.NotificationCollector.issueNotificationsForInsertion(NotificationCollector.java:161) 
        at org.gervarro.democles.incremental.emf.NotificationCollector.add(NotificationCollector.java:143) 
        at org.gervarro.democles.incremental.emf.ResourceLoadingMarker.notifyChanged(ResourceLoadingMarker.java:29) `
