### ISSUE TITLE
Failing assertions in Democles during deletion

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#37]
Hi Greg, 

now that CSPs are working (yay!) it's time to come back to handling deletion and attribute changes properly.

We have been testing for a while by switching off assertions so that all tests run (we now have more than 500 tests).

As I'm sure your assertions are there for a good reason we should identify and solve the underlying problem.  Either we are still not deleting "correctly" in IBeX or some of your assertions in Democles are perhaps wrong or too strict (whatever that might mean).

To reproduce please:

1.  Install the latest version of Ibex from our update site:  https://emoflon.github.io/emoflon-ibex-democles/org.emoflon.ibex.tgg.ide.democles.updatesite/
2.  Check out our test workspace using this PSF:  https://raw.githubusercontent.com/eMoflon/emoflon-ibex-tests/master/testProjectSet.psf
3.  Execute ```/Testsuite/Testsuite.launch``` to run all tests (note assertions are switched off in the launch configuration!).  All tests should be green (ignore Gurobi errors as you probably don't have that).
4.  Now switch assertions back on in the launch configuration and re-run all tests.   You should have 31 failures all due to the same assertion (as far as I can judge) in Democles.

Cheers and thanks,
Tony

**Comment by gervarro** [comment]
Hi Tony,

could you please build a new update site for Ibex and eMoflon Core to avoid the situation that I have to re-install everything for Eclipse Oxygen (the version numbers in eMoflon Core are already fixed)?

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

I just re-deployed.  Please check if this now works for you.

Cheers,
Tony

**Comment by anthonyanjorin** [comment]
Ok I see I have to deploy eMoflon-core, I’ll do that right away.

**Comment by gervarro** [comment]
Hi Tony,

I uploaded a fix to the problem, although it does not cover all cases yet. The previously failing test cases should be hopefully green now.

Btw. relatively many tests failed on my computer due to a `NullPointerException` in the TGG part at `org.emoflon.ibex.tgg.compiler.patterns.common.AbstractCorrPattern.extractSourceAndTargetEdges(AbstractCorrPattern.java:31)`. I am wondering whether you also faced this problem.

Bests,
Greg

**Comment by gervarro** [comment]
Just a further comment: this was a bug.

**Comment by anthonyanjorin** [comment]
Thanks, Greg!

I just updated and tried out the test suite.  I still get assertion failures :(
How about we focus on a particular test (all the rest probably fail for the same or similar reasons)?

A simple test would be:  ```testsuite.ibex.ClassInhHier2DB_MA.sync.SyncBackward.testDeleteTableThatIsSubClass_BWD()```

This test passes for me if assertions are switched off, but fails if they are switched on with:
```
java.lang.AssertionError
	at org.gervarro.democles.runtime.HistoryBasedIteratorHandler.lookupNextFrame(HistoryBasedIteratorHandler.java:131)
	at org.gervarro.democles.runtime.HistoryBasedIteratorHandler.<init>(HistoryBasedIteratorHandler.java:55)
	at org.gervarro.democles.runtime.HistoryBasedInterpretableOperation.getDataFrame(HistoryBasedInterpretableOperation.java:52)
	at org.gervarro.democles.runtime.QueryableRemappingOperation.getDataFrameProvider(QueryableRemappingOperation.java:57)
	at org.gervarro.democles.runtime.InternalBidirectionalOperation.lookupInternalDataFrameProvider(InternalBidirectionalOperation.java:38)
	at org.gervarro.democles.runtime.InternalBidirectionalOperation.lookupInternalDataFrameProvider(InternalBidirectionalOperation.java:1)
	at org.gervarro.democles.runtime.JoinOperation.execute(JoinOperation.java:37)
	at org.gervarro.democles.runtime.EventHandlingTask.perform(EventHandlingTask.java:37)
	at org.gervarro.democles.common.runtime.Session.run(Session.java:34)
	at org.gervarro.democles.runtime.IncrementalUpdateSession.call(IncrementalUpdateSession.java:143)
	at org.gervarro.democles.interpreter.incremental.rete.RetePatternMatcherModule.performIncrementalUpdates(RetePatternMatcherModule.java:115)
	at org.emoflon.ibex.gt.democles.runtime.DemoclesGTEngine.updateMatches(DemoclesGTEngine.java:269)
	at org.emoflon.ibex.tgg.operational.strategies.OperationalStrategy.run(OperationalStrategy.java:311)
	at org.emoflon.ibex.tgg.operational.strategies.sync.SYNC.backward(SYNC.java:90)
	at testsuite.ibex.testUtil.IbexAdapter.performAndPropagateTargetEdit(IbexAdapter.java:40)
	at testsuite.ibex.ClassInhHier2DB_MA.sync.SyncBackward.testDeleteTableThatIsSubClass_BWD(SyncBackward.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by gervarro** [comment]
Hi Tony,

I refined (weakened) the assertion. Please rebuild IBeX from source and check whether this helps.

While analyzing the erroneous situation, I found some strange behaviour at some points that might need to be checked.

- Set a breakpoint to the `performAndPropagateTargetEdit` line (https://github.com/eMoflon/emoflon-ibex-tests/blob/ed5bf2dc383deac9a6eae021219eb8e7aa5b689e/testsuites/Testsuite/test/testsuite/ibex/ClassInhHier2DB_MA/sync/SyncBackward.java#L51). When you go through that method step-by-step, there are only deletions carried out, however, when the incremental pattern matcher starts processing the notifications, many insert events come first, which means that some earlier phases have not been committed (i.e., `performIncrementalUpdates`). Is it an intentional behaviour or a bug? 
- If I noticed correctly, the expected models are loaded into the same resource set that also contains the models under test. This results in a situation that the expected models are also fed into the incremental pattern matcher, which obviously causes longer runtimes as the model size is doubled, and cross-joins (disjunct patterns) might be affected even more seriously. The `NotificationProcessor` can be installed not only on the whole resource set https://github.com/eMoflon/emoflon-ibex-democles/blob/852d2902fba7296e9522c0702641931b5648da5b/org.emoflon.ibex.gt.democles/src/org/emoflon/ibex/gt/democles/runtime/DemoclesGTEngine.java#L263 but also on individual resources. Note that this is an experimental feature.

Bests,
Greg
