### ISSUE TITLE
Illegal Access Exception in Democles

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#46]
Hi Greg,

[A student of mine is waiting for this so a quick fix would be very much appreciated]

@Arikae has had this problem before:  due to some methods in Democles with package visibility, an IllegalAccessError flies when this method is invoked from a different bundle (or whatever).

Could you please change the visibility of ```submitDataFrame``` in ```org.gervarro.democles.runtime.NativeOperation```  from package to public?  This should solve the problem (as it already did for @Arikae).

FYI:  this is the stack trace for the error:
```
java.lang.IllegalAccessError: tried to access method org.gervarro.democles.runtime.NativeOperation.submitDataFrame(Lorg/gervarro/democles/common/runtime/SessionedDataFrame;Ljava/lang/String;)V from class org.gervarro.democles.runtime.IncrementalUpdateSession
	at org.gervarro.democles.runtime.IncrementalUpdateSession.call(IncrementalUpdateSession.java:140)
	at org.gervarro.democles.interpreter.incremental.rete.RetePatternMatcherModule.performIncrementalUpdates(RetePatternMatcherModule.java:115)
	at org.emoflon.ibex.gt.democles.runtime.DemoclesGTEngine.updateMatches(DemoclesGTEngine.java:258)
	at org.emoflon.ibex.tgg.operational.strategies.OperationalStrategy.run(OperationalStrategy.java:311)
	at org.emoflon.ibex.tgg.operational.strategies.sync.SYNC.forward(SYNC.java:85)
	at com.kaleidoscope.usecase.showcase.xmlexcel.artefactadapter.PersonArtefactAdapter.lambda$0(PersonArtefactAdapter.java:38)
	at com.kaleidoscope.usecase.showcase.xmlexcel.artefactadapter.PersonArtefactAdapter$$Lambda$454/1059784568.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.kaleidoscope.usecase.showcase.xmlexcel.artefactadapter.PersonArtefactAdapter.parse(PersonArtefactAdapter.java:35)
	at com.kaleidoscope.core.framework.workflow.controllers.statebased.StateBasedController.syncForward(StateBasedController.java:45)
	at com.kaleidoscope.core.framework.workflow.controllers.statebased.PersistentStateBasedController.syncForward(PersistentStateBasedController.java:54)
	at com.kaleidoscope.usecase.showcase.first.eclipse.Builder.syncForward(Builder.java:108)
	at com.kaleidoscope.usecase.showcase.first.eclipse.Builder.visit(Builder.java:158)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at com.kaleidoscope.usecase.showcase.first.eclipse.Builder.generateFilesIfchangeIsRelevant(Builder.java:93)
	at com.kaleidoscope.usecase.showcase.first.eclipse.Builder.build(Builder.java:66)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by gervarro** [comment]
Done. The latest version should be available on the update site.

**Comment by anthonyanjorin** [comment]
Hi Greg,

I'm now getting the same exception for the package visible methods in ```org.gervarro.democles.runtime.EventHandlingTask<LO extends Operation, RO extends Operation>```

**Comment by anthonyanjorin** [comment]
Hi Greg,

could you please change the visibility of these methods?  Hopefully these are the last ones :)

Cheers and thanks,
Tony

**Comment by gervarro** [comment]
Hi Tony,

I made these methods public, and the updates are available on the update site. I carried out some reorganization in the packages. IBeX has to be rebuilt from source, as the deployed version is most probably incompatible with the latest Democles interpreter.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Thanks, Greg.

I’ll do this ASAP and get back to you if I have any problems.

Cheers,
Tony
