### ISSUE TITLE
Errors in tests after update to latest Democles version

### ISSUE THREAD

**Issue by patrickrobrecht** [eMoflon/emoflon-ibex-democles#51]
Error when running the GTTestsuite:

```
java.lang.NoSuchMethodError:
org.gervarro.democles.operation.emf.EMFBatchOperationBuilder: method
<init>(Lorg/gervarro/democles/common/runtime/OperationBuilder;Lorg/gervarro/democles/common/runtime/AdornmentAssignmentStrategy;)V
not found
    at org.emoflon.ibex.gt.democles.runtime.DemoclesGTEngine.configureDemocles(DemoclesGTEngine.java:205)
    at org.emoflon.ibex.gt.democles.runtime.DemoclesGTEngine.createAndRegisterPatterns(DemoclesGTEngine.java:149)
    at
org.emoflon.ibex.gt.democles.runtime.DemoclesGTEngine.initPatterns(DemoclesGTEngine.java:132)
    at
org.emoflon.ibex.gt.engine.GraphTransformationInterpreter.loadPatternSet(GraphTransformationInterpreter.java:191)
    at
org.emoflon.ibex.gt.engine.GraphTransformationInterpreter.loadPatternSet(GraphTransformationInterpreter.java:210)
    at
SheRememberedCaterpillarsGraphTransformation.api.SheRememberedCaterpillarsGraphTransformationAPI.<init>(SheRememberedCaterpillarsGraphTransformationAPI.java:51)
    at
org.emoflon.ibex.gt.testsuite.SheRememberedCaterpillars.SheRememberedCaterpillarsTest.getAPI(SheRememberedCaterpillarsTest.java:31)
    at
org.emoflon.ibex.gt.testsuite.SheRememberedCaterpillars.SheRememberedCaterpillarsTest.getAPI(SheRememberedCaterpillarsTest.java:1)
    at org.emoflon.ibex.gt.testsuite.GTTestCase.initAPI(GTTestCase.java:84)
    at
org.emoflon.ibex.gt.testsuite.SheRememberedCaterpillars.SheRememberedCaterpillarsTest.testIllegalSituation(SheRememberedCaterpillarsTest.java:60)
```

....

Error when running the Testsuite for TGGs:

```
java.lang.NoSuchMethodError:
org.gervarro.democles.operation.emf.EMFBatchOperationBuilder: method
<init>(Lorg/gervarro/democles/common/runtime/OperationBuilder;Lorg/gervarro/democles/common/runtime/AdornmentAssignmentStrategy;)V
not found
    at org.emoflon.ibex.gt.democles.runtime.DemoclesGTEngine.configureDemocles(DemoclesGTEngine.java:205)
    at
org.emoflon.ibex.gt.democles.runtime.DemoclesGTEngine.createAndRegisterPatterns(DemoclesGTEngine.java:149)
    at
org.emoflon.ibex.tgg.runtime.engine.DemoclesTGGEngine.initPatterns(DemoclesTGGEngine.java:70)
    at
org.emoflon.ibex.tgg.runtime.engine.DemoclesTGGEngine.setOptions(DemoclesTGGEngine.java:52)
    at
org.emoflon.ibex.tgg.operational.strategies.OperationalStrategy.initialiseBlackInterpreter(OperationalStrategy.java:223)
    at
org.emoflon.ibex.tgg.operational.strategies.OperationalStrategy.registerBlackInterpreter(OperationalStrategy.java:148)
    at
org.emoflon.ibex.tgg.operational.strategies.sync.SYNC.registerBlackInterpreter(SYNC.java:39)
    at
org.emoflon.ibex.tgg.run.classmultipleinhhier2db_ma.SYNC_App.<init>(SYNC_App.java:18)
    at
testsuite.ibex.ClassMultiInhHier2DB_MA.sync.util.IbexMultiIhnCD2DB_MA.initiateSynchronisationDialogue(IbexMultiIhnCD2DB_MA.java:24)
    at testsuite.ibex.testUtil.SyncTestCase.initialise(SyncTestCase.java:26)
 
...
```

The errors occur after updating eMoflon::IBeX which updates org.gervarro.democles.interpreter.incremental,
org.gervarro.democles.interpreter.incremental.emf and
org.gervarro.democles.interpreter to version 1.0.0v20180303-23xx.

**Comment by patrickrobrecht** [comment]
@gervarro Can you help us with this issue? All tests are failing with this Democles error (reproducable when installing eMoflon::IBeX in a fresh Eclipse Modeling Tools).

**Comment by gervarro** [comment]
I fixed bugs and reorganized content in some projects yesterday. I do not know exactly how IBeX deployment is carried out, but this seems to be an incompatibility issue between the latest Democles and a deployed IBeX installation. My guess is that IBeX has to be built from source, and after redeployment, everything should work fine.

@anthonyanjorin: Could you please build a new deployable IBeX?

If you installed Democles from the update site, then you can uninstall the latest version of the interpreter (Help -> Install New Software... -> What is already installed? -> Select Democles interpreter -> Uninstall), and reinstall a previous version. Uncheck the 'Show only the latest versions of available software' checkbox on the installation page, and the older versions will also appear on the list.
